DROP TABLE IF EXISTS t_platform;
CREATE TABLE t_platform(
id      INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
name    VARCHAR(16) NOT NULL COMMENT '平台名称',
linkman VARCHAR(32) NOT NULL COMMENT '平台联系人',
img     VARCHAR(64) COMMENT '平台图片',
intro   VARCHAR(64) COMMENT '平台描述',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
)ENGINE=InnoDB DEFAULT CHARSET=UTF8 COMMENT='平台表';


DROP TABLE IF EXISTS t_api;
CREATE TABLE t_api(
id          INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
platform_id INT NOT NULL COMMENT '平台ID，对应t_platform#id',
name        VARCHAR(8) NOT NULL COMMENT 'API名称',
content     MEDIUMTEXT NOT NULL COMMENT 'API内容',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
)ENGINE=InnoDB DEFAULT CHARSET=UTF8 COMMENT='API表';